services:
  db:
    image: postgres
    container_name: dartscore_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: <<username>>
      POSTGRES_PASSWORD: <<password>>
    volumes:
      - db:/var/lib/postgresql/data 
  dartscore:
    image: mxwnk/dartscore
    container_name: dartscore
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URL: "postgres://<<username>>:<<password>>@dartscore_db:5432/dartscore_db"

volumes:
  db: