name: Build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        # must be set for prisma generate cmd
        POSTGRES_PRISMA_URL: "postgresql://admin:password@localhost:5432/dart"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - run: npm install
      - run: npm run lint
      - run: npm run db:generate
      - run: npm run build
      - run: npm run test
  deploy:
      runs-on: ubuntu-latest
      needs: build
      if: github.ref == 'refs/heads/main'
      permissions:
        contents: read
        packages: write
        attestations: write
        id-token: write
      steps:
        - uses: actions/checkout@v2
        - uses: docker/setup-buildx-action@v1
        - uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: mxwnk/dartscore:latest
            platforms: linux/amd64, linux/arm64
